/* Реестр витрины локальных компонентов — меню и карточки страниц apps/local-components/.

   СГЕНЕРИРОВАН kit-build.mjs из паспортов виджетов (apps/<раздел>/<модуль>/widgets/<группа>/<Имя>/<Имя>.md)
   и project.json → localKit. Руками не править: пересобрать — node .agents/tools/kit-build.mjs
   (гейт сверяет, шаг kit).

   Обычный <script>, а не JSON: страницы открываются по file://, где fetch не работает.

   Поля компонента: id — папка виджета; name, category, purpose, version, updated —
   из паспорта; type — tile | table | modal | popover | context-menu | part (подчасть);
   module — <раздел>/<модуль>; doc — страница компонента от папки витрины; owner —
   id компонента, чей это артефакт (окно, поповер), или null; stub — заглушка. */
window.IBPKit = {
  "title": "Локальные компоненты",
  "categories": [
    "Общие",
    "Сделка",
    "Инструменты",
    "Отчёты",
    "Другое"
  ],
  "components": [
    {
      "id": "CounterpartiesEcmModal",
      "name": "Модальное окно «Документы по сделке»",
      "category": "Сделка",
      "purpose": "Выбрать участника сделки и открыть его документы ЭКД",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/CounterpartiesEcmModal.doc.html",
      "owner": "DealDescriptionTile",
      "stub": false,
      "version": "1.002",
      "updated": "27.09.2026"
    },
    {
      "id": "CounterpartiesTile",
      "name": "Контрагенты",
      "category": "Сделка",
      "purpose": "Показать контрагентов сущности (на странице сделки — ключевых носителей риска) с рейтингом и зоной проблемности и дать точку входа в их выбор",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/CounterpartiesTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "0.010",
      "updated": "25.09.2026"
    },
    {
      "id": "CounterpartyCard",
      "name": "Карточка контрагента",
      "category": "Общие",
      "purpose": "Контрагент сделки — юрлицо или физлицо — карточкой: наименование, реквизиты, рейтинг и отметка КНР",
      "type": "part",
      "typeLabel": "подчасть",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/CounterpartyCard.doc.html",
      "owner": null,
      "stub": false,
      "version": "0.006",
      "updated": "25.09.2026"
    },
    {
      "id": "DealCounterpartiesTable",
      "name": "Контрагенты сделки",
      "category": "Сделка",
      "purpose": "Реестр контрагентов сделки с ролями, связанными инструментами и обеспечениями, ОСЗ, ВБС и зоной проблемности",
      "type": "table",
      "typeLabel": "таблица",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealCounterpartiesTable.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "24.09.2026"
    },
    {
      "id": "DealDescriptionModal",
      "name": "Модальное окно описания сделки",
      "category": "Сделка",
      "purpose": "Заполнить и поправить описание сделки, её признаки и группу связанных заемщиков",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealDescriptionModal.doc.html",
      "owner": "DealDescriptionTile",
      "stub": false,
      "version": "1.000",
      "updated": "25.09.2026"
    },
    {
      "id": "DealDescriptionTile",
      "name": "Описание сделки",
      "category": "Сделка",
      "purpose": "Суть сделки, комментарий Operations, признаки сделки и группа связанных заемщиков",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealDescriptionTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.003",
      "updated": "25.09.2026"
    },
    {
      "id": "DealFinancialMetricsModal",
      "name": "Модальное окно финансовых метрик сделки",
      "category": "Сделка",
      "purpose": "Финансовые метрики сделки целиком — ВБС и ОСЗ, резервы по ФИ, переоценка по PE по ФИ",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealFinancialMetricsModal.doc.html",
      "owner": "DealFinancialMetricsTile",
      "stub": false,
      "version": "1.002",
      "updated": "27.09.2026"
    },
    {
      "id": "DealFinancialMetricsTile",
      "name": "Финансовые метрики сделки",
      "category": "Сделка",
      "purpose": "ВБС сделки в разрезе продуктов, резерв, обесценение, RWA и переоценка по PE — сводка с входом в окно метрик",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealFinancialMetricsTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.002",
      "updated": "27.09.2026"
    },
    {
      "id": "DealMetricsCalculationTile",
      "name": "Финансовые метрики",
      "category": "Сделка",
      "purpose": "Расчёт финансовых метрик по инструментам сделки и выгрузка отчётов",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealMetricsCalculationTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "22.09.2026"
    },
    {
      "id": "DealPeriodModal",
      "name": "Модальное окно сроков сделки",
      "category": "Сделка",
      "purpose": "Ввести дату первой выдачи, сверяясь с датами заключения и окончания сделки",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealPeriodModal.doc.html",
      "owner": "DealPeriodTile",
      "stub": false,
      "version": "0.004",
      "updated": "23.09.2026"
    },
    {
      "id": "DealPeriodTile",
      "name": "Сроки сделки",
      "category": "Сделка",
      "purpose": "Ключевые даты сделки — заключение, окончание и первая выдача — и точка входа в ввод даты первой выдачи",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealPeriodTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "0.006",
      "updated": "30.09.2026"
    },
    {
      "id": "DealProductTreeTile",
      "name": "Продукты сделки",
      "category": "Сделка",
      "purpose": "Дерево продуктов сделки — продукты ДИД, продукты, инструменты и транши с номерами, основной продукт и точки входа в добавление, удаление, погашение, перенос и связь с ФИ",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealProductTreeTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.003",
      "updated": "30.09.2026"
    },
    {
      "id": "DealProjectInformationModal",
      "name": "Модальное окно сведений о проекте",
      "category": "Сделка",
      "purpose": "Заполнить и поправить сведения о проекте недвижимости и его метрики",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealProjectInformationModal.doc.html",
      "owner": "ProjectInformationTile",
      "stub": false,
      "version": "1.000",
      "updated": "28.09.2026"
    },
    {
      "id": "DealRelatedCollateralsTile",
      "name": "Связанные обеспечения",
      "category": "Сделка",
      "purpose": "Реестр обеспечений сделки: залоги, поручительства, гарантии",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealRelatedCollateralsTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "22.09.2026"
    },
    {
      "id": "DealSetupTile",
      "name": "Заведение сделки",
      "category": "Сделка",
      "purpose": "Навигатор заведения сделки: степпер этапов по контурам и переход к следующему шагу",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealSetupTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.004",
      "updated": "22.09.2026"
    },
    {
      "id": "DealTeamModal",
      "name": "Модальное окно команды сделки",
      "category": "Сделка",
      "purpose": "Назначить деск и участников сделки и отметить сделку ограниченного доступа",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealTeamModal.doc.html",
      "owner": "DealTeamTile",
      "stub": false,
      "version": "1.000",
      "updated": "23.09.2026"
    },
    {
      "id": "DealTeamTile",
      "name": "Команда сделки",
      "category": "Сделка",
      "purpose": "Ответственные по сделке — деск и роли участников, с точкой входа в правку состава",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealTeamTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.001",
      "updated": "25.09.2026"
    },
    {
      "id": "DidProductsModal",
      "name": "Окно «Продукты ДИД»",
      "category": "Сделка",
      "purpose": "Выбрать продукты ДИД сделки — добавить из справочника с обязательным составом и убрать выбранные",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DidProductsModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.002",
      "updated": "30.09.2026"
    },
    {
      "id": "EpsVbsImpactTile",
      "name": "Влияние на ЭПС/ВБС",
      "category": "Сделка",
      "purpose": "Расчёт влияния модификации на ЭПС и ВБС по сделке",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/EpsVbsImpactTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "22.09.2026"
    },
    {
      "id": "FinInstrumentsTile",
      "name": "Финансовые инструменты",
      "category": "Сделка",
      "purpose": "Финансовые инструменты сделки с параметрами лимита, контрагентами и вложенными инструментами",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/FinInstrumentsTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.004",
      "updated": "22.09.2026"
    },
    {
      "id": "InstrumentsCounterpartiesModal",
      "name": "Модальное окно контрагентов",
      "category": "Сделка",
      "purpose": "Найти контрагентов, перенести их в участники сделки и отметить среди них ключевых носителей риска",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/InstrumentsCounterpartiesModal.doc.html",
      "owner": "CounterpartiesTile",
      "stub": false,
      "version": "0.007",
      "updated": "24.09.2026"
    },
    {
      "id": "InstrumentsModal",
      "name": "Окно «Инструменты»",
      "category": "Сделка",
      "purpose": "Выбрать инструменты одного продукта сделки — добавить из доступных типов и убрать выбранные",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/InstrumentsModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "30.09.2026"
    },
    {
      "id": "InstrumentTransferModal",
      "name": "Окно «Перенос инструмента»",
      "category": "Сделка",
      "purpose": "Перенести инструмент в другой подходящий продукт этой же сделки",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/InstrumentTransferModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "30.09.2026"
    },
    {
      "id": "LinkChangeModal",
      "name": "Окно «Изменить связь с ФИ»",
      "category": "Сделка",
      "purpose": "Прикрепить инструмент или транш к одной-двум карточкам ФИ сделки или снять связь",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/LinkChangeModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "30.09.2026"
    },
    {
      "id": "ProductsModal",
      "name": "Окно «Продукты»",
      "category": "Сделка",
      "purpose": "Выбрать продукты одного продукта ДИД сделки — добавить из доступных и убрать выбранные",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/ProductsModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.002",
      "updated": "30.09.2026"
    },
    {
      "id": "ProductTreeConfirmModal",
      "name": "Подтверждение действия над деревом",
      "category": "Сделка",
      "purpose": "Подтвердить удаление узла дерева продуктов или назначение основного продукта ДИД",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/ProductTreeConfirmModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "30.09.2026"
    },
    {
      "id": "ProjectInformationTile",
      "name": "Сведения о проекте",
      "category": "Сделка",
      "purpose": "Параметры проекта недвижимости — тип, класс жилья, регион и город — и метрики проекта на момент одобрения на КПКИ",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/ProjectInformationTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "28.09.2026"
    },
    {
      "id": "RelatedDealsPopover",
      "name": "Поповер связанных сделок",
      "category": "Сделка",
      "purpose": "Показать связанные сделки клиента ссылками на них",
      "type": "popover",
      "typeLabel": "поповер",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/RelatedDealsPopover.doc.html",
      "owner": "DealDescriptionTile",
      "stub": false,
      "version": "1.002",
      "updated": "27.09.2026"
    },
    {
      "id": "RepaymentModal",
      "name": "Окно погашения",
      "category": "Сделка",
      "purpose": "Погасить инструмент или транш вручную с датой фактического погашения или отменить погашение",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/RepaymentModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "30.09.2026"
    }
  ]
};
