/* Реестр витрины локальных компонентов — меню и карточки страниц apps/local-components/.

   СГЕНЕРИРОВАН kit-build.mjs из паспортов виджетов (apps/<раздел>/<модуль>/widgets/<группа>/<Имя>/<Имя>.md)
   и project.json → localKit. Руками не править: пересобрать — node .agents/tools/kit-build.mjs
   (гейт сверяет, шаг kit).

   Обычный <script>, а не JSON: страницы открываются по file://, где fetch не работает.

   Поля компонента: id — папка виджета; name, category, purpose, version, updated —
   из паспорта; type — tile | table | modal | popover | context-menu | part (подчасть);
   module — <раздел>/<модуль>; doc — страница компонента от папки витрины; owner —
   id компонента, чей это артефакт (окно, поповер), или null; stub — заглушка. */
window.IBPKit = {
  "title": "Локальные компоненты",
  "categories": [
    "Общие",
    "Сделка",
    "Инструменты",
    "Отчёты",
    "Другое"
  ],
  "components": [
    {
      "id": "DateBadge",
      "name": "Блок даты",
      "category": "Общие",
      "purpose": "День и месяц «листком календаря» в ведущем слоте строки встречи; сегодняшняя дата — в тоне accent",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/DateBadge.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "HomeProfileTile",
      "name": "Профиль на главной",
      "category": "Другое",
      "purpose": "Кто вошёл — фото, имя, должность и деск, связь — и быстрый вход в создание встречи и задачи",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/HomeProfileTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "MeetingCreateModal",
      "name": "Новая встреча",
      "category": "Другое",
      "purpose": "Быстро назначить встречу с клиентом с главной — клиент, тема, дата и время",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/MeetingCreateModal.doc.html",
      "owner": "MeetingsTile",
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "MeetingsTile",
      "name": "Встречи",
      "category": "Другое",
      "purpose": "Ближайшие встречи с клиентами — свои или деска, с выборками «сегодня», «на неделе», «требует внимания»",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/MeetingsTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "MyDayTile",
      "name": "Мой день",
      "category": "Другое",
      "purpose": "Сегодняшние встречи по времени и горящие сроки задач — с переходом к нужной выборке в один клик",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/MyDayTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "NewsTile",
      "name": "Новости по клиентам",
      "category": "Другое",
      "purpose": "Свежие публикации о клиентах сотрудника или деска — повод для звонка и тема встречи",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/NewsTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "StatCard",
      "name": "Карточка-счётчик",
      "category": "Общие",
      "purpose": "Число с подписью и тоном, по клику включает выборку списка — счётчики встреч и задач главной",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/StatCard.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "TaskCreateModal",
      "name": "Новая задача",
      "category": "Другое",
      "purpose": "Быстро поставить себе задачу с главной — формулировка, срок, приоритет, клиент и сделка",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/TaskCreateModal.doc.html",
      "owner": "TasksTile",
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "TasksTile",
      "name": "Задачи",
      "category": "Другое",
      "purpose": "Открытые задачи по срочности — свои или деска, с выборками «новые», «сегодня», «просрочено» и сменой статуса на месте",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "core/drafts/new-dashboard-mvp",
      "doc": "core/drafts/new-dashboard-mvp/TasksTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "09.10.2026"
    },
    {
      "id": "CounterpartiesEcmModal",
      "name": "Модальное окно «Документы по сделке»",
      "category": "Сделка",
      "purpose": "Выбрать участника сделки и открыть его документы ЭКД",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/CounterpartiesEcmModal.doc.html",
      "owner": "DealDescriptionTile",
      "stub": false,
      "version": "1.002",
      "updated": "02.10.2026"
    },
    {
      "id": "CounterpartiesTile",
      "name": "Контрагенты",
      "category": "Сделка",
      "purpose": "Показать контрагентов сущности (на странице сделки — ключевых носителей риска) с рейтингом и зоной проблемности и дать точку входа в их выбор",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/CounterpartiesTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "0.010",
      "updated": "02.10.2026"
    },
    {
      "id": "CounterpartyCard",
      "name": "Карточка контрагента",
      "category": "Общие",
      "purpose": "Контрагент сделки — юрлицо или физлицо — карточкой: наименование, реквизиты, рейтинг и отметка КНР",
      "type": "part",
      "typeLabel": "подчасть",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/CounterpartyCard.doc.html",
      "owner": null,
      "stub": false,
      "version": "0.006",
      "updated": "02.10.2026"
    },
    {
      "id": "DealCounterpartiesTable",
      "name": "Контрагенты сделки",
      "category": "Сделка",
      "purpose": "Реестр контрагентов сделки с ролями, связанными инструментами и обеспечениями, ОСЗ, ВБС и зоной проблемности",
      "type": "table",
      "typeLabel": "таблица",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealCounterpartiesTable.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "02.10.2026"
    },
    {
      "id": "DealDescriptionModal",
      "name": "Модальное окно описания сделки",
      "category": "Сделка",
      "purpose": "Заполнить и поправить описание сделки, её признаки и группу связанных заемщиков",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealDescriptionModal.doc.html",
      "owner": "DealDescriptionTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "DealDescriptionTile",
      "name": "Описание сделки",
      "category": "Сделка",
      "purpose": "Суть сделки, комментарий Operations, признаки сделки и группа связанных заемщиков",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealDescriptionTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.003",
      "updated": "02.10.2026"
    },
    {
      "id": "DealFinancialInstrumentCreateModal",
      "name": "Окно «Создание финансового инструмента»",
      "category": "Сделка",
      "purpose": "Создать карточку финансового инструмента сделки — выбрать тип ФИ и тип отчётности",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealFinancialInstrumentCreateModal.doc.html",
      "owner": "FinInstrumentsTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "DealFinancialInstrumentEditModal",
      "name": "Окно «ФИ — изменение»",
      "category": "Сделка",
      "purpose": "Поправить параметры карточки финансового инструмента — наименование, контрагентов, FV/AC, IRR, признаки",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealFinancialInstrumentEditModal.doc.html",
      "owner": "FinInstrumentsTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "DealFinancialMetricsModal",
      "name": "Модальное окно финансовых метрик сделки",
      "category": "Сделка",
      "purpose": "Финансовые метрики сделки целиком — ВБС и ОСЗ, резервы по ФИ, переоценка по PE по ФИ",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealFinancialMetricsModal.doc.html",
      "owner": "DealFinancialMetricsTile",
      "stub": false,
      "version": "1.004",
      "updated": "04.10.2026"
    },
    {
      "id": "DealFinancialMetricsTile",
      "name": "Финансовые метрики сделки",
      "category": "Сделка",
      "purpose": "ВБС сделки в разрезе продуктов, резерв, обесценение, RWA и переоценка по PE — сводка с входом в окно метрик",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealFinancialMetricsTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.003",
      "updated": "04.10.2026"
    },
    {
      "id": "DealMetricsCalculationTile",
      "name": "Финансовые метрики",
      "category": "Сделка",
      "purpose": "Расчёт финансовых метрик по инструментам сделки и выгрузка отчётов",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealMetricsCalculationTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "02.10.2026"
    },
    {
      "id": "DealPeriodModal",
      "name": "Модальное окно сроков сделки",
      "category": "Сделка",
      "purpose": "Ввести дату первой выдачи, сверяясь с датами заключения и окончания сделки",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealPeriodModal.doc.html",
      "owner": "DealPeriodTile",
      "stub": false,
      "version": "0.004",
      "updated": "02.10.2026"
    },
    {
      "id": "DealPeriodTile",
      "name": "Сроки сделки",
      "category": "Сделка",
      "purpose": "Ключевые даты сделки — заключение, окончание и первая выдача — и точка входа в ввод даты первой выдачи",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealPeriodTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "0.006",
      "updated": "02.10.2026"
    },
    {
      "id": "DealProductTreeTile",
      "name": "Продукты сделки",
      "category": "Сделка",
      "purpose": "Дерево продуктов сделки — продукты ДИД, продукты, инструменты и транши с номерами, основной продукт и точки входа в добавление, удаление, погашение, перенос и связь с ФИ",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealProductTreeTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.003",
      "updated": "02.10.2026"
    },
    {
      "id": "DealProjectInformationModal",
      "name": "Модальное окно сведений о проекте",
      "category": "Сделка",
      "purpose": "Заполнить и поправить сведения о проекте недвижимости и его метрики",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealProjectInformationModal.doc.html",
      "owner": "ProjectInformationTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "DealRelatedCollateralsTile",
      "name": "Связанные обеспечения",
      "category": "Сделка",
      "purpose": "Реестр обеспечений сделки: залоги, поручительства, гарантии",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealRelatedCollateralsTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "02.10.2026"
    },
    {
      "id": "DealSetupTile",
      "name": "Заведение сделки",
      "category": "Сделка",
      "purpose": "Навигатор заведения сделки: степпер этапов по контурам и переход к следующему шагу",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealSetupTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.004",
      "updated": "02.10.2026"
    },
    {
      "id": "DealTeamModal",
      "name": "Модальное окно команды сделки",
      "category": "Сделка",
      "purpose": "Назначить деск и участников сделки и отметить сделку ограниченного доступа",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealTeamModal.doc.html",
      "owner": "DealTeamTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "DealTeamTile",
      "name": "Команда сделки",
      "category": "Сделка",
      "purpose": "Ответственные по сделке — деск и роли участников, с точкой входа в правку состава",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealTeamTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.001",
      "updated": "02.10.2026"
    },
    {
      "id": "DealTitleModal",
      "name": "Модальное окно редактирования сделки",
      "category": "Сделка",
      "purpose": "Поменять номер и наименование сделки",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DealTitleModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "DidProductsModal",
      "name": "Окно «Продукты ДИД»",
      "category": "Сделка",
      "purpose": "Выбрать продукты ДИД сделки — добавить из справочника с обязательным составом и убрать выбранные",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/DidProductsModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.002",
      "updated": "02.10.2026"
    },
    {
      "id": "EpsVbsImpactTile",
      "name": "Влияние на ЭПС/ВБС",
      "category": "Сделка",
      "purpose": "Расчёт влияния модификации на ЭПС и ВБС по сделке",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/EpsVbsImpactTile.doc.html",
      "owner": null,
      "stub": true,
      "version": "0.003",
      "updated": "02.10.2026"
    },
    {
      "id": "FinInstrumentsTile",
      "name": "Финансовые инструменты",
      "category": "Сделка",
      "purpose": "Финансовые инструменты сделки — карточки ФИ с параметрами, контрагентами и прикреплёнными инструментами дерева продуктов",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/FinInstrumentsTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.001",
      "updated": "04.10.2026"
    },
    {
      "id": "InstrumentsCounterpartiesModal",
      "name": "Модальное окно контрагентов",
      "category": "Сделка",
      "purpose": "Найти контрагентов, перенести их в участники сделки и отметить среди них ключевых носителей риска",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/InstrumentsCounterpartiesModal.doc.html",
      "owner": "CounterpartiesTile",
      "stub": false,
      "version": "0.007",
      "updated": "02.10.2026"
    },
    {
      "id": "InstrumentsModal",
      "name": "Окно «Инструменты»",
      "category": "Сделка",
      "purpose": "Выбрать инструменты одного продукта сделки — добавить из доступных типов и убрать выбранные",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/InstrumentsModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "InstrumentTransferModal",
      "name": "Окно «Перенос инструмента»",
      "category": "Сделка",
      "purpose": "Перенести инструмент в другой подходящий продукт этой же сделки",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/InstrumentTransferModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "LinkChangeModal",
      "name": "Окно «Изменить связь с ФИ»",
      "category": "Сделка",
      "purpose": "Прикрепить инструмент или транш к одной-двум карточкам ФИ сделки или снять связь",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/LinkChangeModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.001",
      "updated": "02.10.2026"
    },
    {
      "id": "ProductsModal",
      "name": "Окно «Продукты»",
      "category": "Сделка",
      "purpose": "Выбрать продукты одного продукта ДИД сделки — добавить из доступных и убрать выбранные",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/ProductsModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.002",
      "updated": "02.10.2026"
    },
    {
      "id": "ProductTreeConfirmModal",
      "name": "Подтверждение действия над деревом",
      "category": "Сделка",
      "purpose": "Подтвердить удаление узла дерева продуктов или назначение основного продукта ДИД",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/ProductTreeConfirmModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "ProjectInformationTile",
      "name": "Сведения о проекте",
      "category": "Сделка",
      "purpose": "Параметры проекта недвижимости — тип, класс жилья, регион и город — и метрики проекта на момент одобрения на КПКИ",
      "type": "tile",
      "typeLabel": "тайл",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/ProjectInformationTile.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "RelatedDealsPopover",
      "name": "Поповер связанных сделок",
      "category": "Сделка",
      "purpose": "Показать связанные сделки клиента ссылками на них",
      "type": "popover",
      "typeLabel": "поповер",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/RelatedDealsPopover.doc.html",
      "owner": "DealDescriptionTile",
      "stub": false,
      "version": "1.002",
      "updated": "02.10.2026"
    },
    {
      "id": "RepaymentModal",
      "name": "Окно погашения",
      "category": "Сделка",
      "purpose": "Погасить инструмент или транш вручную с датой фактического погашения или отменить погашение",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/deals-app",
      "doc": "postrade/deals-app/RepaymentModal.doc.html",
      "owner": "DealProductTreeTile",
      "stub": false,
      "version": "1.000",
      "updated": "02.10.2026"
    },
    {
      "id": "CreateFairValueCalculationModal",
      "name": "Окно формирования нового расчета FV",
      "category": "Отчёты",
      "purpose": "Задать дату и сформировать новый расчет FV",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/post-reports-app",
      "doc": "postrade/post-reports-app/CreateFairValueCalculationModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "08.10.2026"
    },
    {
      "id": "DownloadReportModal",
      "name": "Выгрузка расчета FV",
      "category": "Отчёты",
      "purpose": "Подтвердить выгрузку файла с данными K2 и, в сети с шифрованием, выбрать сотрудников, которым он будет доступен",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/post-reports-app",
      "doc": "postrade/post-reports-app/DownloadReportModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "08.10.2026"
    },
    {
      "id": "FairValueInstrumentablesUploadFileModal",
      "name": "Окно «Данные по инструменту»",
      "category": "Отчёты",
      "purpose": "Показать содержимое загружаемого XML-файла инструмента и принять загрузку",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/post-reports-app",
      "doc": "postrade/post-reports-app/FairValueInstrumentablesUploadFileModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "08.10.2026"
    },
    {
      "id": "FairValueUserMetricsModal",
      "name": "Окно ФИ расчета FV",
      "category": "Отчёты",
      "purpose": "Показать ФИ, поправить рейтинг, LGD, ставку ПАО и комментарий, управлять файлами инструментов",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/post-reports-app",
      "doc": "postrade/post-reports-app/FairValueUserMetricsModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "08.10.2026"
    },
    {
      "id": "ReservesFvComponentsModal",
      "name": "Окно «Данные FV» с компонентами",
      "category": "Отчёты",
      "purpose": "Показать предпросмотр загруженного файла компонентов FV перед сохранением",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/post-reports-app",
      "doc": "postrade/post-reports-app/ReservesFvComponentsModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "08.10.2026"
    },
    {
      "id": "ReservesFvModal",
      "name": "Окно «Данные FV»",
      "category": "Отчёты",
      "purpose": "Показать предпросмотр загруженного файла FV перед сохранением",
      "type": "modal",
      "typeLabel": "модальное окно",
      "module": "postrade/post-reports-app",
      "doc": "postrade/post-reports-app/ReservesFvModal.doc.html",
      "owner": null,
      "stub": false,
      "version": "1.000",
      "updated": "08.10.2026"
    }
  ]
};
