/* Конструктор. История и несохранённое живут только в памяти этого документа. */
(function(){
  'use strict';var T=window.DS_THEMES,R=window.DS_RAMP,E=window.DS_THEME_ENGINE,F=window.DSThemeFiles,A=window.DSTheme;
  var $=function(id){return document.getElementById(id);},clone=function(x){return JSON.parse(JSON.stringify(x));},esc=function(v){return String(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  function prepare(file){var copy=clone(file);['light','dark'].forEach(function(m){if(copy[m]){copy[m].overrides=copy[m].overrides||{};copy[m].adjust=copy[m].adjust||{};}});return copy;}
  function releaseService(p,m){if(m!=='dark')return;var fixed=Object.assign({},T.values,T.themeValues.service);Object.keys(p.overrides).forEach(function(k){if(k.indexOf('--ramp-accent-')===0||k.indexOf('--ramp-neutral-')===0){var tone=k.slice(7,k.lastIndexOf('-')),step=k.slice(k.lastIndexOf('-')+1);if(p.overrides[k]===R.tone(T.seeds.service.ramps[tone],'dark')[step])delete p.overrides[k];}else if(/--ramp-(accent|neutral)-/.test(fixed[k]||'')&&p.overrides[k]===fixed[k])delete p.overrides[k];});}
  var data=window.DS_THEME_DATA,choice=A.selection(),original=data.themes.find(function(f){return f.name===choice.name;})||data.themes[0],draft=prepare(original),mode=choice.mode||'light',history=[clone(draft)],cursor=0,dirty=false,picker=null,suppress=false;
  function profile(){return draft[mode];}
  function lists(){var selected=draft.name;$('theme-file').innerHTML=A.files().map(function(f){return '<option value="'+esc(f.name)+'">'+esc(f.label)+(f.locked?' · 🔒':'')+'</option>';}).join('');$('theme-file').value=selected;}
  function load(name,m){if(picker){picker.destroy();picker=null;}original=data.themes.find(function(f){return f.name===name;});draft=prepare(original);mode=m==='dark'&&draft.dark?'dark':'light';history=[clone(draft)];cursor=0;dirty=false;A.set(name,mode);render();}
  function snapshot(){var next=JSON.stringify(draft);if(next===JSON.stringify(history[cursor]))return;history=history.slice(0,cursor+1);history.push(clone(draft));if(history.length>100)history.shift();cursor=history.length-1;dirty=next!==JSON.stringify(prepare(original));}
  function change(fn,source){fn();snapshot();render(source);}
  function undo(dir){var index=cursor+dir;if(index<0||index>=history.length)return;cursor=index;draft=clone(history[cursor]);dirty=JSON.stringify(draft)!==JSON.stringify(prepare(original));if(picker){picker.destroy();picker=null;}if(!dirty)A.set(draft.name,mode);render();}
  function colorFormat(hex){if($('export-format').value==='oklch'&&/^#[\da-f]{6}$/i.test(hex)){var v=R.hexToOklch(hex);return 'oklch('+(v.l*100).toFixed(2)+'% '+v.c.toFixed(4)+' '+v.h.toFixed(2)+')';}return hex;}
  function button(label,attrs){return '<button type="button" class="btn btn--transparent btn--xs" '+attrs+'><span class="btn__label">'+esc(label)+'</span></button>';}
  function swatch(k,value,step,small,manual){var fg=/^#[\da-f]{6}$/i.test(value)?(R.contrast('#FFFFFF',value)>=R.contrast('#111112',value)?'#FFFFFF':'#111112'):'var(--text-primary)';return '<button type="button" class="theme-swatch'+(small?' theme-swatch--small':'')+'" data-edit="'+esc(k)+'" style="--sw:'+esc(value)+';--sw-fg:'+fg+'" aria-label="Изменить '+esc(k)+'">'+(step?'<span>'+esc(step)+(step==='500'?' ●':'')+'</span>':'')+'<span class="theme-swatch__hex">'+esc(value)+'</span>'+(step&&/^#[\da-f]{6}$/i.test(value)?'<span class="theme-swatch__contrast">'+Math.max(R.contrast('#FFFFFF',value),R.contrast('#111112',value)).toFixed(1)+':1</span>':'')+(manual?'<span class="theme-swatch__manual">Ручная</span>':'')+'</button>';}
  function ramps(model,tones,target,prefix){$(target).innerHTML=tones.map(function(t){return '<div class="theme-ramp"><span class="theme-ramp__name">'+esc(t==='accent'?'Brand':t==='neutral'?'Neutral':t)+'</span>'+R.STEPS.map(function(s){var k='--ramp-'+t+'-'+s;return swatch(k,model.ramps[t][s],s,false,!!profile().overrides[k]);}).join('')+'</div>';}).join('');}
  function tables(model){
    var groups={};Object.keys(T.roles).forEach(function(k){var g=T.roles[k].group;(groups[g]||(groups[g]=[])).push(k);});
    $('theme-roles').innerHTML=Object.keys(groups).map(function(g,i){return '<details class="theme-role-group"'+(i===0?' open':'')+'><summary>'+esc(g)+' · '+groups[g].length+'</summary><table class="theme-table"><thead><tr><th>Роль</th><th>Назначение</th><th>Цвет</th><th>Действия</th></tr></thead><tbody>'+groups[g].map(function(k){return '<tr><td><code>'+esc(k)+'</code>'+(profile().overrides[k]?'<br>Ручная правка':'')+'</td><td>'+esc(T.roles[k].desc)+'</td><td>'+swatch(k,model.colors[k],null,true,false)+'</td><td><div class="theme-table__actions">'+button('Копировать','data-copy="'+esc(k)+'"')+(profile().overrides[k]?button('Сбросить','data-reset="'+esc(k)+'"'):'')+'</div></td></tr>';}).join('')+'</tbody></table></details>';}).join('');
    $('theme-map').innerHTML='<table class="theme-table"><thead><tr><th>Старое имя</th><th>Роль</th><th>Действия</th></tr></thead><tbody>'+Object.keys(T.map).map(function(k){return '<tr><td><code>'+esc(k)+'</code></td><td><code>'+esc(T.map[k])+'</code></td><td>'+button('Изменить роль','data-edit="'+esc(T.map[k])+'"')+'</td></tr>';}).join('')+'</tbody></table>';
    contrastTable(model);
  }
  function contrastTable(model){
    $('theme-contrast').innerHTML='<table class="theme-table"><thead><tr><th>Пара</th><th>Минимум</th><th>Контраст</th><th>Результат</th></tr></thead><tbody>'+model.contrast.map(function(p){var fixed=p.exempt&&p.exempt.indexOf(mode==='light'?'ibp-light':draft.name==='custom'?'service':'ibp-dark')>=0;return '<tr'+(p.ratio!==null&&p.ratio<p.min?' class="theme-contrast-fail"':'')+'><td><code>'+esc(p.fg)+'</code> / <code>'+esc(p.bg)+'</code></td><td>'+p.min+':1</td><td>'+(p.ratio===null?'Составной цвет':p.ratio.toFixed(2)+':1')+'</td><td>'+(p.ratio===null?'Проверить визуально':p.ratio>=p.min?'✓ AA':fixed?'⚠ Фиксированный цвет':'⚠ Ниже AA')+'</td></tr>';}).join('')+'</tbody></table>';
  }
  function render(source){
    var compiled=clone(draft);if(dirty&&compiled.name==='ibp-legacy'){compiled.name='theme-preview';compiled.locked=false;}var model=E.compile(compiled,mode,data),p=profile();
    if(dirty){var view=clone(draft);if(view.name==='ibp-legacy'){view.name='theme-preview';view.locked=false;}suppress=true;A.preview(view,mode);suppress=false;}
    $('theme-mode').checked=mode==='dark';$('theme-mode').disabled=!draft.dark;$('theme-status').textContent=dirty?'Не сохранено':draft.locked?'Базовая тема · сохранена':'Сохранено';$('theme-save').disabled=!!draft.locked||!dirty;$('theme-undo').disabled=cursor===0;$('theme-redo').disabled=cursor===history.length-1;
    ['brand','neutral'].forEach(function(k){if(source!==k)$('theme-'+k).value=p[k];});
    ['hue','saturation','temperature'].forEach(function(k){var input=$('adjust-'+k);input.value=(p.adjust||{})[k]||0;window.DSSlider.bind(input.closest('.slr')).sync();});
    $('theme-onfill').checked=p.onFill==='dark';
    if(source!=='picker'){ramps(model,['accent','neutral'],'theme-palettes');tables(model);}else{
      document.querySelectorAll('[data-edit]').forEach(function(el){if(!el.classList.contains('theme-swatch'))return;var k=el.dataset.edit,v=k.indexOf('--ramp-')===0?model.ramps[k.slice(7,k.lastIndexOf('-'))][k.slice(k.lastIndexOf('-')+1)]:model.colors[k];el.style.setProperty('--sw',v);el.querySelector('.theme-swatch__hex').textContent=v;var ratio=el.querySelector('.theme-swatch__contrast');if(ratio&&/^#[\da-f]{6}$/i.test(v))ratio.textContent=Math.max(R.contrast('#FFFFFF',v),R.contrast('#111112',v)).toFixed(1)+':1';if(/^#[\da-f]{6}$/i.test(v))el.style.setProperty('--sw-fg',R.contrast('#FFFFFF',v)>=R.contrast('#111112',v)?'#FFFFFF':'#111112');if(profile().overrides[k]&&!el.querySelector('.theme-swatch__manual')){var marker=document.createElement('span');marker.className='theme-swatch__manual';marker.textContent='Ручная';el.appendChild(marker);}});
    }
    if(source==='picker')contrastTable(model);
    var baseMode=$('base-mode').value,baseDraft=clone(draft);if(!baseDraft[baseMode])baseDraft[baseMode]={brand:p.brand,neutral:p.neutral,overrides:{},adjust:{},onFill:'white'};
    var base=E.compile(baseDraft,baseMode,data);if(source!=='picker')$('theme-base').innerHTML=Object.keys(data.bases[baseMode].ramps).map(function(t){return '<div class="theme-ramp"><span class="theme-ramp__name">'+esc(t)+'</span>'+R.STEPS.map(function(s){var k='--ramp-'+t+'-'+s;return swatch(k,base.ramps[t][s],s,false,!!baseDraft[baseMode].overrides[k]).replace('data-edit=','data-base-edit=');}).join('')+'</div>';}).join('');
    else $('theme-base').querySelectorAll('[data-base-edit]').forEach(function(el){var k=el.dataset.baseEdit,v=base.ramps[k.slice(7,k.lastIndexOf('-'))][k.slice(k.lastIndexOf('-')+1)];el.style.setProperty('--sw',v);el.querySelector('.theme-swatch__hex').textContent=v;});
    var css=E.css(model);if(!css)css='/* IBP Legacy — без data-theme. Значения текущей ДС. */\n:root {\n'+Object.keys(model.old).map(function(k){return '  '+k+': '+model.old[k]+';';}).join('\n')+'\n}';
    if($('export-format').value==='oklch')css=css.replace(/#[\da-f]{6}/gi,colorFormat);
    $('theme-export-json').textContent=JSON.stringify(draft,null,2);$('theme-export-css').textContent=css;
    $('theme-preview-name').textContent=draft.label+' · '+(mode==='dark'?'Тёмная':'Светлая');
  }
  function readHex(k){var model=E.compile(draft,mode,data),value=k.indexOf('--ramp-')===0?model.ramps[k.slice(7,k.lastIndexOf('-'))][k.slice(k.lastIndexOf('-')+1)]:model.colors[k];if(/^#[\da-f]{6}$/i.test(value))return value;var el=document.createElement('span');el.style.color=value;document.body.appendChild(el);var computed=getComputedStyle(el).color;el.remove();var canvas=document.createElement('canvas');canvas.width=canvas.height=1;var ctx=canvas.getContext('2d');ctx.fillStyle=computed;ctx.fillRect(0,0,1,1);var rgb=ctx.getImageData(0,0,1,1).data;return '#'+Array.from(rgb).slice(0,3).map(function(n){return n.toString(16).padStart(2,'0');}).join('').toUpperCase();}
  function edit(trigger,k,baseMode){if(picker)picker.destroy();var editMode=baseMode||mode;if(!draft[editMode]){$('theme-error').textContent='У IBP Legacy нет тёмного профиля. Сохраните тему под новым именем';return;}var value;if(baseMode){value=E.compile(draft,baseMode,data).ramps[k.slice(7,k.lastIndexOf('-'))][k.slice(k.lastIndexOf('-')+1)];}else value=readHex(k);
    picker=window.DSColorPicker.bind(trigger,{value:value,onChange:function(v){change(function(){draft[editMode].overrides[k]=v;},'picker');},onReset:function(){if(picker){picker.destroy();picker=null;}change(function(){delete draft[editMode].overrides[k];});}});picker.open();
  }
  $('pane-constructor').addEventListener('click',function(e){var b=e.target.closest('[data-edit],[data-base-edit],[data-reset],[data-copy]');if(!b)return;if(b.dataset.edit)edit(b,b.dataset.edit);else if(b.dataset.baseEdit)edit(b,b.dataset.baseEdit,$('base-mode').value);else if(b.dataset.reset)change(function(){delete profile().overrides[b.dataset.reset];});else window.DSCopy.write(colorFormat(readHex(b.dataset.copy))).then(function(){window.DSCopy.flash(b,'Скопировано');});});
  $('theme-file').onchange=function(){if(dirty&&!confirm('Несохранённые изменения будут потеряны. Переключить тему?')){$('theme-file').value=draft.name;return;}load(this.value,mode);};
  $('theme-mode').onchange=function(){if(picker){picker.destroy();picker=null;}mode=this.checked?'dark':'light';if(!dirty)A.set(draft.name,mode);render();};
  ['brand','neutral'].forEach(function(k){$('theme-'+k).onchange=function(){var input=this;if(!/^#[\da-f]{6}$/i.test(input.value)){input.setAttribute('aria-invalid','true');$('theme-error').textContent='Введите цвет в формате #RRGGBB';return;}input.removeAttribute('aria-invalid');$('theme-error').textContent='';change(function(){['light','dark'].forEach(function(m){if(draft[m]){draft[m][k]=input.value.toUpperCase();releaseService(draft[m],m);}});},k);};$('theme-'+k).addEventListener('input',function(){this.onchange();});$('pick-'+k).onclick=function(e){e.stopImmediatePropagation();if(picker)picker.destroy();picker=window.DSColorPicker.bind(this,{value:profile()[k],onChange:function(v){$('theme-'+k).value=v;$('theme-'+k).onchange();}});picker.open();};});
  ['hue','saturation','temperature'].forEach(function(k){$('adjust-'+k).oninput=function(){var value=Number(this.value);change(function(){['light','dark'].forEach(function(m){if(draft[m]){draft[m].adjust=draft[m].adjust||{};draft[m].adjust[k]=value;releaseService(draft[m],m);}});});};});
  $('theme-onfill').onchange=function(){var on=this.checked;change(function(){profile().onFill=on?'dark':'white';delete profile().overrides['--color-fg-on-fill'];delete profile().overrides['--color-accent-fill'];});};
  $('theme-generate').onclick=function(){var seeds=R.generate($('theme-method').value);change(function(){['light','dark'].forEach(function(m){if(draft[m]){draft[m].brand=seeds.brand;draft[m].neutral=seeds.neutral;draft[m].adjust={hue:0,saturation:0,temperature:0};draft[m].overrides={};}});});};
  $('theme-code').onclick=function(){$('tab-code').click();};
  $('theme-reset').onclick=function(){change(function(){profile().overrides={};profile().adjust={hue:0,saturation:0,temperature:0};});};
  $('theme-undo').onclick=function(){undo(-1);};$('theme-redo').onclick=function(){undo(1);};
  document.addEventListener('keydown',function(e){if(e.target.closest('input,textarea,select,[contenteditable],.cpk,.modal-scrim')||$('pane-constructor').hidden)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1);}else if(e.code==='Space'){e.preventDefault();$('theme-generate').click();}});
  $('base-mode').onchange=function(){render();};$('export-format').onchange=function(){render();};
  $('theme-copy-json').onclick=function(){window.DSCopy.write($('theme-export-json').textContent).then(function(){window.DSCopy.flash($('theme-copy-json'),'Скопировано');});};$('theme-copy-css').onclick=function(){window.DSCopy.write($('theme-export-css').textContent).then(function(){window.DSCopy.flash($('theme-copy-css'),'Скопировано');});};
  $('theme-download').onclick=function(){F.download(draft);};
  $('theme-connect').onclick=async function(){try{data=await F.connect();A.reload(data);lists();$('theme-connect').querySelector('.btn__label').textContent='Папка подключена';$('theme-error').textContent='';}catch(e){if(e.name!=='AbortError')$('theme-error').textContent=e.message;}};
  async function save(file,create){try{data=await F.save(file,{create:create,original:create?null:original});original=clone(file);draft=clone(file);dirty=false;history=[clone(draft)];cursor=0;lists();A.set(file.name,mode);render();return true;}catch(e){$('theme-error').textContent=e.message;return false;}}
  $('theme-save').onclick=function(){save(draft,false);};
  $('save-name').addEventListener('input',function(){$('save-error').textContent='';});
  $('theme-save-as').addEventListener('click',function(){$('save-name').value='';$('save-label').value=draft.label;$('save-error').textContent='';});
  $('save-confirm').onclick=async function(){var file=clone(draft);file.name=$('save-name').value.trim();file.label=$('save-label').value.trim();file.locked=false;if(!file.dark){file.dark={brand:file.light.brand,neutral:file.light.neutral,adjust:clone(file.light.adjust),overrides:{},onFill:'white'};}
    var errors=E.validate(file);if(errors.length){$('save-error').textContent=errors.join('; ');return;}if(!F.connected()){$('save-error').textContent='Подключите папку tokens перед сохранением';return;}
    if(await save(file,true))window.DSModal.closeTop();else $('save-error').textContent=$('theme-error').textContent;
  };
  addEventListener('beforeunload',function(e){if(dirty){e.preventDefault();e.returnValue='';}});
  document.addEventListener('ds:themechange',function(){if(suppress)return;var s=A.selection();if((s.name!==draft.name||s.mode!==mode)&&data.themes.some(function(f){return f.name===s.name;})&&!dirty)load(s.name,s.mode);});
  document.addEventListener('ds:themelistchange',function(){data=window.DS_THEME_DATA;lists();});
  var states=[['Обычная',''],['Наведение',' is-hover'],['Нажатие',' is-active'],['Включена',' is-pressed'],['Недоступна',''],['Загрузка',' btn--loading']];
  $('theme-preview-buttons').innerHTML=['accent','outline','transparent'].map(function(type){return '<div class="theme-preview__row"><span class="ds-body-s">'+type+'</span>'+states.map(function(state,index){return '<button type="button" class="btn btn--'+type+' btn--s'+state[1]+'"'+(index>=4?' disabled':'')+(index===3?' aria-pressed="true"':'')+(index===5?' aria-busy="true"':'')+'>'+(index===5?'<span class="spin spin--xs" aria-hidden="true"></span>':'')+'<span class="btn__label">'+state[0]+'</span></button>';}).join('')+'</div>';}).join('');
  lists();render();F.restore().then(function(handle){if(handle)$('theme-connect').querySelector('.btn__label').textContent='Папка подключена';});
})();
